/*
 * Copyright (C) 2010 Aday Talavera Hierro <aday.talavera@gmail.com>
 *
 * This file is part of JASEIMOV.
 *
 * JASEIMOV is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JASEIMOV is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JASEIMOV.  If not, see <http://www.gnu.org/licenses/>.
 */
package client.maingui.dialogs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

/**
 * JDialog that allows the user to choose the lenguage of JASEIMOV client application.
 * @author Aday Talavera Hierro <aday.talavera@gmail.com>
 */
public class LanguageDialog extends javax.swing.JDialog implements ActionListener

{    
    public LanguageDialog(java.awt.Frame parent)
    {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);

        englishButton.addActionListener(this);
        spanishButton.addActionListener(this);
    }

    public void actionPerformed(ActionEvent e)
    {
        Object obj = e.getSource();
        Locale locale;
        if(obj.equals(englishButton))
        {
            locale = Locale.ENGLISH;
        }        
        else //Spanish button
        {
            locale = new Locale("ES","es");
        }
        new SelectLanguageCommand(locale).execute();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        englishButton = new javax.swing.JButton();
        spanishButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("client/client"); // NOI18N
        setTitle(bundle.getString("LANGUAGE DIALOG TITLE")); // NOI18N

        englishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/english.gif"))); // NOI18N
        englishButton.setText(bundle.getString("LANGUAGE ENGLISH")); // NOI18N
        englishButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        englishButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        spanishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/spanish.png"))); // NOI18N
        spanishButton.setText(bundle.getString("LANGUAGE SPANISH")); // NOI18N
        spanishButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        spanishButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setText(bundle.getString("LANGUAGE QUESTION 1")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(englishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spanishButton))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(englishButton)
                    .addComponent(spanishButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton englishButton;
    javax.swing.JButton spanishButton;
    // End of variables declaration//GEN-END:variables

}
