/*
 * Copyright (C) 2010 Aday Talavera Hierro <aday.talavera@gmail.com>
 *
 * This file is part of JASEIMOV.
 *
 * JASEIMOV is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JASEIMOV is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JASEIMOV.  If not, see <http://www.gnu.org/licenses/>.
 */
package jaseimov.client.maingui.sensorvisors;

/**
 * A JPanel that shows one data of a sensor.
 * @author Aday Talavera Hierro <aday.talavera@gmail.com>
 */
class SensorPanel extends javax.swing.JPanel
{ 
    public SensorPanel(String name, String magnitude)
    {
        initComponents();

        nameLabel.setText(name);
        magnitudeLabel.setText(magnitude);
    }

    public void setVariable(String text)
    {
        variableField.setText(text);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        variableField = new javax.swing.JTextField();
        magnitudeLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        nameLabel.setText("variable name:");
        add(nameLabel);

        variableField.setEditable(false);
        variableField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variableField.setText("123789.456789");
        add(variableField);

        magnitudeLabel.setText("magnitude");
        add(magnitudeLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel magnitudeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField variableField;
    // End of variables declaration//GEN-END:variables

}
